### ISSUE TITLE
HDRJPGs with resolutions higher than 4K crash on mobile (iOS iPhone 15)

### ISSUE THREAD

**Issue by kitaedesigns** [MONOGRID/gainmap-js#40] opened 2024-04-15 19:11 UTC
Using a HDRJPG with higher resolutions than 4096 in width seem to crash mobile webpage. Not sure if this is due to iOS and some Safari artificial VRAM limitations or something in the codebase but my guess is iOS. Above 4K HDRJPGs seem to work fine on iPad Pro M2 fine, and desktops as well. Gotten up to 6K on iPad Pro and 8K on desktop.

Curious to hear if anyone else has encountered this problem.

**Comment by kitaedesigns** [comment] 2024-04-17 03:37
Here is the code and a link for mobile to test. You can see that when you switch from 4K to 8K it renders black on mobile

Video
https://github.com/MONOGRID/gainmap-js/assets/23407511/9903f92b-b017-4640-a0f5-18ecdc7a0b5b

Code
https://stackblitz.com/~/github.com/ianpetrarca/gainmap

Test Link for Mobile
https://gainmap-ef100.web.app/

**Comment by daniele-pelagatti** [comment] 2024-04-17 08:40
at first glance the problem can be reproduced on android and your page can be inspected with `chrome://inspect`, this is the result:
![image](https://github.com/MONOGRID/gainmap-js/assets/19731017/9653c0d7-e94b-4bf8-8faa-2a7c39436f0a)


the source of the log

```
THREE.WebGLRenderer: Texture has been resized from (8192x4096) to (4096x2048).
```

seems to be this line in threejs

https://github.com/mrdoob/three.js/blob/34cfc4d11cf0a0fd83dc66a75acfc181df9bc972/src/renderers/webgl/WebGLTextures.js#L85

so apparently there's a limit of some kind (which I ignore the motivation behind) and three.js tries to resize the texture and (apparently) fails to display the resized texture.

I'm going to close this for now as this doesn't appear to be a gainmap.js related problem

**Closed by daniele-pelagatti** 2024-04-17 08:40 UTC

**Comment by GitHubDragonFly** [comment] 2025-01-18 22:32
Just to mention that this also seems to be an issue with textures larger than 16k - this is apparently the limit of THREE.WebGLRenderer which will try to resize the texture to 16384xscaled_height (whatever the height might be).

For a test just resize any JPG image to something higher than 16384 and try to load it.

It appears that the `renderTarget` still retains the image's original dimensions.
