### ISSUE TITLE
No “exports” main defined in @monogrid/gainmap-js

### ISSUE THREAD

**Issue by drcmda** [MONOGRID/gainmap-js#35] opened 2024-04-03 09:19 UTC
now that monogrid is in drei users experience issues with bundling environments like next-js.

https://discourse.threejs.org/t/trying-to-use-react-three-drei-in-next-js-error-no-exports-main-defined-in-monogrid-gainmap-js-package-json/63586

```shell
Server Error
Error: No “exports” main defined in /Users/primozrome/Documents/WEB/dewesoft-website/node_modules/@monogrid/gainmap-js/package.json
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

**Comment by daniele-pelagatti** [comment] 2024-04-03 09:25
is this solved by adding something like this?
```json
  "exports": {
    ".": {
      "import": "./dist/decode.js",
      "main":  "./dist/decode.umd.js", <----------
      "types": "./dist/decode.d.ts"
    },
    "./encode": {
      "import": "./dist/encode.js",
      "main":  "./dist/encode.umd.js", <----------      
      "types": "./dist/encode.d.ts"
    },
    "./libultrahdr": {
      "import": "./dist/libultrahdr.js",
      "main":  "./dist/libultrahdr.umd.js", <----------      
      "types": "./dist/libultrahdr.d.ts"
    },
    "./worker": {
      "import": "./dist/worker.js",
      "main":  "./dist/worker.umd.js", <----------            
      "types": "./dist/worker.d.ts"
    },
    "./worker-interface": {
      "import": "./dist/worker-interface.js",
      "main":  "./dist/worker-interface.umd.js", <----------                  
      "types": "./dist/worker-interface.d.ts"
    }
  },
```

I'm not sure what's the proper fix, I have no trouble bundling with vite

**Comment by daniele-pelagatti** [comment] 2024-04-03 09:38
or maybe I need to name the files `.mjs` 
```json
[...]
  "exports": {
    ".": {
      "import": "./dist/decode.mjs",
      [...]
    }
[...]
```

:thinking: 
I'm trying to reproduce the problem with  https://github.com/pmndrs/react-three-next

**Comment by drcmda** [comment] 2024-04-03 09:40
good idea! i hope this is just a fluke. esm exports package.json is so complicated, i would not know how to even publish a package nowadays.

**Comment by CodyJasonBennett** [comment] 2024-04-03 09:50
See https://publint.dev/@monogrid/gainmap-js@3.0.4. It should be (note the use of `.cjs`):

```json
"main": "dist/decode.umd.cjs",
"module": "dist/decode.js",
"types": "dist/decode.d.ts",
"sideEffects": false,
"type": "module",
"exports": {
  ".": {
    "types": "./dist/decode.d.ts",
    "import": "./dist/decode.js",
    "default":  "./dist/decode.umd.cjs"
  },
  "./encode": {
    "types": "./dist/encode.d.ts",
    "import": "./dist/encode.js",
    "default":  "./dist/encode.umd.cjs"
  },
  "./libultrahdr": {
    "types": "./dist/libultrahdr.d.ts",
    "import": "./dist/libultrahdr.js",
    "default":  "./dist/libultrahdr.umd.cjs"
  },
  "./worker": {
    "types": "./dist/worker.d.ts",
    "import": "./dist/worker.js",
    "main":  "./dist/worker.umd.cjs"
  },
  "./worker-interface": {
    "types": "./dist/worker-interface.d.ts",
    "import": "./dist/worker-interface.js",
    "default":  "./dist/worker-interface.umd.js"
  }
},
```

**Comment by daniele-pelagatti** [comment] 2024-04-03 10:03
Ok, I kinda trust you but I wasn't able to reproduce the problem with a clean https://github.com/pmndrs/react-three-next initialization with the "untouched" library
![image](https://github.com/MONOGRID/gainmap-js/assets/19731017/2757e90c-d41b-4111-966d-856dd8a59e7e)
and a yarn build produced no error
![image](https://github.com/MONOGRID/gainmap-js/assets/19731017/2bee0695-b266-45af-9c12-b217a5cd2fbd)
@CodyJasonBennett can you confirm this would fix the problem? or point me to a reproducibility procedure? I'm the kind of guy that likes to avoids "blind fixes" if possible

**Comment by CodyJasonBennett** [comment] 2024-04-03 10:23
The reason this issue occurred was because Node tried to resolve your package from a CJS entrypoint (Next.js server-side), but the package only specifies the `import` condition (ESM-only). Since Node 14, it reads from the `exports` field over `main` when present (`module` is a Webpack-only field).

The use of `.cjs` or `.mjs` overrides the `type` key which controls which resolver Node should use for `.js` extensions. So, for an ESM package with `"type": "module"`, you can use `.cjs` to specify a CJS entrypoint, and anything ending with `.js` is assumed to be ESM.

I couldn't clone this repository to implement this fix myself, but was referred here due to a downstream issue when resolving with Next.js, presumably through their app directory which uses a different compiler than our Next.js integration tests. https://publint.dev exists and can be used locally via CLI to ensure your package satisfies Node's increasingly complicated API contract.

**Comment by daniele-pelagatti** [comment] 2024-04-03 10:31
Okay then, I've opened #36 with the fix you proposed, will be merging soon

**Comment by daniele-pelagatti** [comment] 2024-04-03 11:16
v3.0.5 is out https://publint.dev/@monogrid/gainmap-js@3.0.5 seems fine, let me know if this solves this problem, thanks for the help!

**Comment by daniele-pelagatti** [comment] 2024-04-05 16:45
I'm going to close this as no-one else reported a similar problem. If this problem resurfaces please feel free to open again, thanks everyone

**Closed by daniele-pelagatti** 2024-04-05 16:45 UTC
